<?php
return [
    'adminEmail'                    => 'no-reply@brickatlas.shop',
    'supportEmail'                  => 'no-reply@brickatlas.shop',
    'senderEmail'                   => 'no-reply@brickatlas.shop',
    'senderName'                    => 'BricksAtlas',
    'user.passwordResetTokenExpire' => 3600,
    'user.verificationTokenExpire'  => 86400,
    'user.passwordMinLength'        => 12,
    'brickset.username'             => '',
    'brickset.password'             => '',
    'brickset.apiKey'               => '',
    'rebrickable.apiKey'            => '',
    'aliexpress.apiBaseUrl'         => 'https://api-sg.aliexpress.com/sync',
    'aliexpress.appKey'             => '',
    'aliexpress.appSecret'          => '',
    'aliexpress.trackingId'         => '',
    'aliexpress.targetCurrency'     => 'USD',
    'aliexpress.targetLanguage'     => 'EN',
    'aliexpress.shipToCountry'      => 'US',
    'frontend.baseUrl'              => '',
    'backend.baseUrl'               => '',
    'schema.organization.name'      => '',
    'schema.organization.url'       => '',
    'schema.organization.logo'      => '',
];
